[versions]
versionName = "1.2.4"
versionCode = "9"

androidMinSdk = "27"
androidTargetSdk = "37"
androidCompileSdk = "37"

jvmTarget = "17"
composeBom = "2026.08.00"

appUpdate = "2.1.0"
konfettiCompose = "2.0.5"
materialVersion = "1.14.0"
activityCompose = "1.13.0"
composecollapsingtoolbar = "1.0.8"
coreKtx = "1.19.0"
coreSplashscreen = "1.2.0"
espressoCore = "3.7.0"
junit = "4.13.2"
lifecycle = "2.11.0"
navigation = "2.10.0"
profileinstaller = "1.4.1"
shadowsPlus = "1.0.4"
fadingEdges = "1.0.4"
kotlinxSerializationJson = "1.11.0"
androidxJunit = "1.3.0"
billingKtx = "9.1.0"

[libraries]
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-foundation-android = { module = "androidx.compose.foundation:foundation-android" }
app-update = { module = "com.google.android.play:app-update", version.ref = "appUpdate" }
app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdate" }
konfetti-compose = { module = "nl.dionsegijn:konfetti-compose", version.ref = "konfettiCompose" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
fadingEdges = { module = "com.github.t8rin:ComposeFadingEdges", version.ref = "fadingEdges" }
material = { module = "com.google.android.material:material", version.ref = "materialVersion" }
shadowsPlus = { module = "com.github.GIGAMOLE:ComposeShadowsPlus", version.ref = "shadowsPlus" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billingKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-material = { module = "androidx.compose.material:material" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
composecollapsingtoolbar = { module = "com.github.GIGAMOLE:ComposeCollapsingToolbar", version.ref = "composecollapsingtoolbar" }
junit = { module = "junit:junit", version.ref = "junit" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
